name: Build mruby-compiler (macOS)
on:
  workflow_call:
  workflow_dispatch:

env:
  MRUBY_DIR: ${{ github.workspace }}/src/MRubyCS.Compiler/mruby
  CONFIG_DIR: ${{ github.workspace }}/src/MRubyCS.Compiler
    
jobs:
  build-macOS:
    runs-on: macos-latest
    outputs:
      artifact-url: ${{ steps.upload-build.artifact-url }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Build mruby-compiler (macOS)
      working-directory: ${{ env.MRUBY_DIR }}
      shell: bash
      run: |
        MRUBY_CONFIG=${{ env.CONFIG_DIR }}/build_config.macOS.rb rake
        
    - uses: actions/upload-artifact@v4
      id: upload-build
      with:
        name: macOS-build
        path: ${{ env.MRUBY_DIR }}/build
