name: Build mruby-compiler (Linux)

on:
  workflow_call:
  workflow_dispatch:
    
env:
  MRUBY_DIR: ${{ github.workspace }}/src/MRubyCS.Compiler/mruby
  CONFIG_DIR: ${{ github.workspace }}/src/MRubyCS.Compiler
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      artifact-url: ${{ steps.upload-build.artifact-url }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        
    - name: Setup aarch64-linux-gnu-gcc
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Build Linux
      working-directory: ${{ env.MRUBY_DIR }}
      run: |
        MRUBY_CONFIG=${{ env.CONFIG_DIR }}/build_config.linux.rb rake
        
    - uses: actions/upload-artifact@v4
      id: upload-build
      with:
        name: linux-build
        path: ${{ env.MRUBY_DIR }}/build

